name: ya2048
description: Just another 2048 game
version: 0.1.0
homepage: https://www.nkode.io/assets/webtech/demos/ya2048
author: Nane Kratzke <nane.kratzke@fh-luebeck.de>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  quiver: '>=0.29.0 <0.30.0'
  pwa: '>=0.1.0 <0.2.0'

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
