name: ya2048
description: Just another 2048 game
version: 0.2.0
homepage: https://github.com/nkratzke/ya2048
author: Nane Kratzke <nane.kratzke@th-luebeck.de>

environment:
  sdk: '>=2.1.0 < 3.0.0'

dependencies:
  quiver: '>=0.29.0 <0.30.0'
  pwa: '>=0.1.0 <0.2.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.0.0

